/**
 * catalog.js — נתוני האתר.
 *
 * זהו התוכן שכל מבקר רואה. הוא נטען לפני שאר הקוד ומתמזג לתוך ברירות
 * המחדל, ועריכות מהפאנל נשמרות מעליו במכשיר המקומי בלבד.
 * כדי לפרסם עריכה לכל המבקרים: פאנל ניהול, ייצוא קובץ אתר,
 * ואז החלפת הקובץ הזה במאגר.
 *
 * נאסף מדף העסק בוולט.
 */
window.CATALOG_SEED = {
  "business": {
    "name": "טוי באק",
    "tagline": "מוצרי עישון · אילת",
    "legalName": "שם העוסק המלא — למילוי",
    "businessId": "מספר עוסק או חברה — למילוי",
    "address": "הזגג 11, אילת 8850713",
    "whatsapp": "972505335323",
    "whatsappDisplay": "050-5335323",
    "hours": "ראשון עד שלישי 08:00–21:45, רביעי וחמישי 08:00–22:45, שישי 08:00–15:15, שבת סגור",
    "accessibilityOfficer": "שם רכז הנגישות — למילוי",
    "accessibilityContact": "טלפון או דואר אלקטרוני — למילוי"
  },
  "hero": {
    "eyebrow": "הזמנות בוואטסאפ",
    "titleA": "המון פריטים.",
    "titleB": "סדר",
    "titleC": "אחד.",
    "lead": "כל מה שיש בחנות, מסודר לפי מחלקות. בוחרים, שולחים הודעה, מקבלים.",
    "ctaPrimary": "למחלקות החנות",
    "ctaSecondary": "הזמנה בוואטסאפ"
  },
  "pages": {
    "about": "טוי באק, הזגג 11 אילת. חנות מוצרי עישון ומגוון מוצרים נלווים, עם משלוחים בעיר.",
    "terms": "תקנון האתר — טיוטה למילוי ולבדיקת עורך דין.",
    "shipping": "מדיניות משלוחים — אזורי חלוקה, זמני אספקה, עלויות ואופן אימות הגיל במסירה.",
    "returns": "מדיניות ביטול והחזרה — זכות ביטול בתוך ארבעה עשר יום, בכפוף לחריגים שבחוק הגנת הצרכן.",
    "privacy": "מדיניות פרטיות — איזה מידע נאסף, לאיזו מטרה, ולמי הוא מועבר.",
    "accessibility": "הצהרת נגישות — האתר נבנה לפי התקן הישראלי 5568 ברמה AA."
  },
  "departments": [
    {
      "id": "dep_tobacco",
      "name": "טבק",
      "order": 1,
      "restricted": true,
      "showImages": true,
      "showDescriptions": true,
      "intro": ""
    },
    {
      "id": "dep_cigs",
      "name": "סיגריות",
      "order": 2,
      "restricted": true,
      "showImages": true,
      "showDescriptions": true,
      "intro": ""
    },
    {
      "id": "dep_lighters",
      "name": "מצתים",
      "order": 6,
      "restricted": false,
      "showImages": true,
      "showDescriptions": true,
      "intro": ""
    }
  ],
  "products": [
    {
      "id": "prd_tobacco_001",
      "deptId": "dep_tobacco",
      "name": "כאמל צהוב | טבק",
      "price": 101.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fb21e896c0fee8a0c76d",
      "imageAlt": "כאמל צהוב | טבק",
      "description": "30 גרם",
      "order": 1
    },
    {
      "id": "prd_tobacco_002",
      "deptId": "dep_tobacco",
      "name": "כאמל לייט | טבק",
      "price": 101.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fb33e896c0fee8a0c76e",
      "imageAlt": "כאמל לייט | טבק",
      "description": "30 גרם",
      "order": 2
    },
    {
      "id": "prd_tobacco_003",
      "deptId": "dep_tobacco",
      "name": "וינסטון לייט | טבק",
      "price": 101.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fb44e896c0fee8a0c76f",
      "imageAlt": "וינסטון לייט | טבק",
      "description": "30 גרם",
      "order": 3
    },
    {
      "id": "prd_tobacco_004",
      "deptId": "dep_tobacco",
      "name": "אמריקן ספיריט כחול",
      "price": 109.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fb5501a83e3323428825",
      "imageAlt": "אמריקן ספיריט כחול",
      "description": "30 גרם",
      "order": 4
    },
    {
      "id": "prd_tobacco_005",
      "deptId": "dep_tobacco",
      "name": "גולדן וירגיניה ירוק",
      "price": 126.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fb6501a83e3323428826",
      "imageAlt": "גולדן וירגיניה ירוק",
      "description": "40 גרם",
      "order": 5
    },
    {
      "id": "prd_tobacco_006",
      "deptId": "dep_tobacco",
      "name": "גולדן וירגיניה לבן",
      "price": 94.3,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fb7901a83e3323428827",
      "imageAlt": "גולדן וירגיניה לבן",
      "description": "30 גרם",
      "order": 6
    },
    {
      "id": "prd_tobacco_007",
      "deptId": "dep_tobacco",
      "name": "טבק מק ברן | שרי",
      "price": 124.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fb89e896c0fee8a0c771",
      "imageAlt": "טבק מק ברן | שרי",
      "description": "40 גרם",
      "order": 7
    },
    {
      "id": "prd_tobacco_008",
      "deptId": "dep_tobacco",
      "name": "טבק מק ברן | וניל",
      "price": 124.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fb99e896c0fee8a0c772",
      "imageAlt": "טבק מק ברן | וניל",
      "description": "40 גרם",
      "order": 8
    },
    {
      "id": "prd_tobacco_009",
      "deptId": "dep_tobacco",
      "name": "טבק מק ברן | אורגינל",
      "price": 124.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fba8e896c0fee8a0c773",
      "imageAlt": "טבק מק ברן | אורגינל",
      "description": "40 גרם",
      "order": 9
    },
    {
      "id": "prd_tobacco_010",
      "deptId": "dep_tobacco",
      "name": "טבק מק ברן | ענבים",
      "price": 124.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fbbb01a83e3323428829",
      "imageAlt": "טבק מק ברן | ענבים",
      "description": "40 גרם",
      "order": 10
    },
    {
      "id": "prd_tobacco_011",
      "deptId": "dep_tobacco",
      "name": "טבק מק ברן | תפוח",
      "price": 124.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fbd701a83e332342882a",
      "imageAlt": "טבק מק ברן | תפוח",
      "description": "40 גרם",
      "order": 11
    },
    {
      "id": "prd_tobacco_012",
      "deptId": "dep_tobacco",
      "name": "טבק מק ברן | שוקולד",
      "price": 124.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fbe901a83e332342882d",
      "imageAlt": "טבק מק ברן | שוקולד",
      "description": "40 גרם",
      "order": 12
    },
    {
      "id": "prd_tobacco_013",
      "deptId": "dep_tobacco",
      "name": "באלי שאג | נטורל",
      "price": 133.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fbf97b7d76e02824b0bc",
      "imageAlt": "באלי שאג | נטורל",
      "description": "40 גרם",
      "order": 13
    },
    {
      "id": "prd_tobacco_014",
      "deptId": "dep_tobacco",
      "name": "באלי שאג | לבן",
      "price": 133.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fc0a7b7d76e02824b0bd",
      "imageAlt": "באלי שאג | לבן",
      "description": "40 גרם",
      "order": 14
    },
    {
      "id": "prd_tobacco_015",
      "deptId": "dep_tobacco",
      "name": "באלי שאג | סילבר",
      "price": 133.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fc1a7b7d76e02824b0be",
      "imageAlt": "באלי שאג | סילבר",
      "description": "40 גרם",
      "order": 15
    },
    {
      "id": "prd_tobacco_016",
      "deptId": "dep_tobacco",
      "name": "באלי שאג | כחול",
      "price": 133.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fc2c7b7d76e02824b0bf",
      "imageAlt": "באלי שאג | כחול",
      "description": "40 גרם",
      "order": 16
    },
    {
      "id": "prd_tobacco_017",
      "deptId": "dep_tobacco",
      "name": "באלי שאג | אדום",
      "price": 133.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fc417b7d76e02824b0c0",
      "imageAlt": "באלי שאג | אדום",
      "description": "40 גרם",
      "order": 17
    },
    {
      "id": "prd_tobacco_018",
      "deptId": "dep_tobacco",
      "name": "באלי שאג | צהוב",
      "price": 133.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fc517b7d76e02824b0c1",
      "imageAlt": "באלי שאג | צהוב",
      "description": "40 גרם",
      "order": 18
    },
    {
      "id": "prd_tobacco_019",
      "deptId": "dep_tobacco",
      "name": "צ'סטרפילד פיין וירגיניה",
      "price": 86.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fc6501a83e332342882e",
      "imageAlt": "צ'סטרפילד פיין וירגיניה",
      "description": "30 גרם",
      "order": 19
    },
    {
      "id": "prd_tobacco_020",
      "deptId": "dep_tobacco",
      "name": "צ'סטרפילד אורגינל",
      "price": 86.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fc7301a83e332342882f",
      "imageAlt": "צ'סטרפילד אורגינל",
      "description": "30 גרם",
      "order": 20
    },
    {
      "id": "prd_tobacco_021",
      "deptId": "dep_tobacco",
      "name": "טבק פאל מאל כחול",
      "price": 88.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a91fc8101a83e3323428830",
      "imageAlt": "טבק פאל מאל כחול",
      "description": "30 גרם",
      "order": 21
    },
    {
      "id": "prd_tobacco_022",
      "deptId": "dep_tobacco",
      "name": "טבק מניטו ירוק אורגני",
      "price": 90.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92fe5f01a83e332342979f",
      "imageAlt": "טבק מניטו ירוק אורגני",
      "description": "יחידה",
      "order": 22
    },
    {
      "id": "prd_tobacco_023",
      "deptId": "dep_tobacco",
      "name": "טבק מניטו וירג'יניה ורוד",
      "price": 90.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92fe7401a83e33234297a1",
      "imageAlt": "טבק מניטו וירג'יניה ורוד",
      "description": "",
      "order": 23
    },
    {
      "id": "prd_tobacco_024",
      "deptId": "dep_tobacco",
      "name": "טבק מרלבורו אדום",
      "price": 101.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92fe977b7d76e02824c025",
      "imageAlt": "טבק מרלבורו אדום",
      "description": "יחידה",
      "order": 24
    },
    {
      "id": "prd_tobacco_025",
      "deptId": "dep_tobacco",
      "name": "טבק מרלבורו לייט",
      "price": 101.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92feb43a9b0b41a1d1da90",
      "imageAlt": "טבק מרלבורו לייט",
      "description": "יחידה",
      "order": 25
    },
    {
      "id": "prd_tobacco_026",
      "deptId": "dep_tobacco",
      "name": "טבק נקסט פיין",
      "price": 110.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92fed73a9b0b41a1d1da92",
      "imageAlt": "טבק נקסט פיין",
      "description": "יחידה",
      "order": 26
    },
    {
      "id": "prd_tobacco_027",
      "deptId": "dep_tobacco",
      "name": "טבק נקסט אורגינל",
      "price": 110.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92fef701a83e33234297a6",
      "imageAlt": "טבק נקסט אורגינל",
      "description": "יחידה",
      "order": 27
    },
    {
      "id": "prd_tobacco_028",
      "deptId": "dep_tobacco",
      "name": "טבק ווינסטון לבן",
      "price": 115.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92ff1201a83e33234297a9",
      "imageAlt": "טבק ווינסטון לבן",
      "description": "יחידה",
      "order": 28
    },
    {
      "id": "prd_cigs_001",
      "deptId": "dep_cigs",
      "name": "מרלבורו לייט",
      "price": 48.3,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92ff3501a83e33234297ac",
      "imageAlt": "מרלבורו לייט",
      "description": "יחידה",
      "order": 1
    },
    {
      "id": "prd_cigs_002",
      "deptId": "dep_cigs",
      "name": "מרלבורו לייט ארוך",
      "price": 49.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a92ff4401a83e33234297ad",
      "imageAlt": "מרלבורו לייט ארוך",
      "description": "יחידה",
      "order": 2
    },
    {
      "id": "prd_cigs_003",
      "deptId": "dep_cigs",
      "name": "מרלבורו אדום",
      "price": 48.3,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93009c7b7d76e02824c041",
      "imageAlt": "מרלבורו אדום",
      "description": "יחידה",
      "order": 3
    },
    {
      "id": "prd_cigs_004",
      "deptId": "dep_cigs",
      "name": "מרלבורו אדום סופט",
      "price": 49.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9300b001a83e33234297c5",
      "imageAlt": "מרלבורו אדום סופט",
      "description": "יחידה",
      "order": 4
    },
    {
      "id": "prd_cigs_005",
      "deptId": "dep_cigs",
      "name": "מרלבורו טאץ",
      "price": 43.7,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9300df7b7d76e02824c043",
      "imageAlt": "מרלבורו טאץ",
      "description": "יחידה",
      "order": 5
    },
    {
      "id": "prd_cigs_006",
      "deptId": "dep_cigs",
      "name": "מרלבורו פיין טאץ",
      "price": 44.85,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9300fa7b7d76e02824c044",
      "imageAlt": "מרלבורו פיין טאץ",
      "description": "יחידה",
      "order": 6
    },
    {
      "id": "prd_cigs_007",
      "deptId": "dep_cigs",
      "name": "מרלבורו טאץ XL",
      "price": 44.85,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93011401a83e33234297c8",
      "imageAlt": "מרלבורו טאץ XL",
      "description": "יחידה",
      "order": 7
    },
    {
      "id": "prd_cigs_008",
      "deptId": "dep_cigs",
      "name": "מרלבורו פלייבור מיקס",
      "price": 48.3,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93013601a83e33234297cb",
      "imageAlt": "מרלבורו פלייבור מיקס",
      "description": "יחידה",
      "order": 8
    },
    {
      "id": "prd_cigs_009",
      "deptId": "dep_cigs",
      "name": "מרלבורו סאמר ספלש",
      "price": 42.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9301537b7d76e02824c046",
      "imageAlt": "מרלבורו סאמר ספלש",
      "description": "יחידה",
      "order": 9
    },
    {
      "id": "prd_cigs_010",
      "deptId": "dep_cigs",
      "name": "מרלבורו דאבל פיוז'ן",
      "price": 42.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93016a7b7d76e02824c048",
      "imageAlt": "מרלבורו דאבל פיוז'ן",
      "description": "יחידה",
      "order": 10
    },
    {
      "id": "prd_cigs_011",
      "deptId": "dep_cigs",
      "name": "מרלבורו פיוז'ן קפסולה",
      "price": 42.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9301853a9b0b41a1d1daab",
      "imageAlt": "מרלבורו פיוז'ן קפסולה",
      "description": "יחידה",
      "order": 11
    },
    {
      "id": "prd_cigs_012",
      "deptId": "dep_cigs",
      "name": "נקסט פיין לייט",
      "price": 41.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9301bb01a83e33234297ce",
      "imageAlt": "נקסט פיין לייט",
      "description": "יחידה",
      "order": 12
    },
    {
      "id": "prd_cigs_013",
      "deptId": "dep_cigs",
      "name": "נקסט פיין לייט ארוך",
      "price": 41.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9301f23a9b0b41a1d1dab1",
      "imageAlt": "נקסט פיין לייט ארוך",
      "description": "יחידה",
      "order": 13
    },
    {
      "id": "prd_cigs_014",
      "deptId": "dep_cigs",
      "name": "נקסט אורגינל אדום",
      "price": 41.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314723a9b0b41a1d1dba4",
      "imageAlt": "נקסט אורגינל אדום",
      "description": "יחידה",
      "order": 14
    },
    {
      "id": "prd_cigs_015",
      "deptId": "dep_cigs",
      "name": "נקסט ריסס קצר",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314833a9b0b41a1d1dba5",
      "imageAlt": "נקסט ריסס קצר",
      "description": "יחידה",
      "order": 15
    },
    {
      "id": "prd_cigs_016",
      "deptId": "dep_cigs",
      "name": "נקסט ריסס ארוך",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314903a9b0b41a1d1dba6",
      "imageAlt": "נקסט ריסס ארוך",
      "description": "יחידה",
      "order": 16
    },
    {
      "id": "prd_cigs_017",
      "deptId": "dep_cigs",
      "name": "נקסט אדג'",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314a13a9b0b41a1d1dba7",
      "imageAlt": "נקסט אדג'",
      "description": "יחידה",
      "order": 17
    },
    {
      "id": "prd_cigs_018",
      "deptId": "dep_cigs",
      "name": "נקסט פיין אדג'",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314b201a83e332342989f",
      "imageAlt": "נקסט פיין אדג'",
      "description": "יחידה",
      "order": 18
    },
    {
      "id": "prd_cigs_019",
      "deptId": "dep_cigs",
      "name": "נקסט לילך",
      "price": 41.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314c101a83e33234298a4",
      "imageAlt": "נקסט לילך",
      "description": "יחידה",
      "order": 19
    },
    {
      "id": "prd_cigs_020",
      "deptId": "dep_cigs",
      "name": "אל אם בלו לייט",
      "price": 44.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314d101a83e33234298a6",
      "imageAlt": "אל אם בלו לייט",
      "description": "יחידה",
      "order": 20
    },
    {
      "id": "prd_cigs_021",
      "deptId": "dep_cigs",
      "name": "אל אם בלו לייט ארוך",
      "price": 44.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314e57b7d76e02824c140",
      "imageAlt": "אל אם בלו לייט ארוך",
      "description": "יחידה",
      "order": 21
    },
    {
      "id": "prd_cigs_022",
      "deptId": "dep_cigs",
      "name": "אל אם אדום",
      "price": 44.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9314f27b7d76e02824c141",
      "imageAlt": "אל אם אדום",
      "description": "יחידה",
      "order": 22
    },
    {
      "id": "prd_cigs_023",
      "deptId": "dep_cigs",
      "name": "אל אם וייב סלימס",
      "price": 44.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9315017b7d76e02824c143",
      "imageAlt": "אל אם וייב סלימס",
      "description": "יחידה",
      "order": 23
    },
    {
      "id": "prd_cigs_024",
      "deptId": "dep_cigs",
      "name": "אל אם קפסולה פורוורד",
      "price": 44.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93150f7b7d76e02824c148",
      "imageAlt": "אל אם קפסולה פורוורד",
      "description": "יחידה",
      "order": 24
    },
    {
      "id": "prd_cigs_025",
      "deptId": "dep_cigs",
      "name": "אל אם קפסולה קליק",
      "price": 40.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93151b3a9b0b41a1d1dbad",
      "imageAlt": "אל אם קפסולה קליק",
      "description": "יחידה",
      "order": 25
    },
    {
      "id": "prd_cigs_026",
      "deptId": "dep_cigs",
      "name": "פרלמנט נייט קצר",
      "price": 55.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93152b3a9b0b41a1d1dbaf",
      "imageAlt": "פרלמנט נייט קצר",
      "description": "יחידה",
      "order": 26
    },
    {
      "id": "prd_cigs_027",
      "deptId": "dep_cigs",
      "name": "פרלמנט נייט ארוך",
      "price": 55.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9315413a9b0b41a1d1dbb0",
      "imageAlt": "פרלמנט נייט ארוך",
      "description": "יחידה",
      "order": 27
    },
    {
      "id": "prd_cigs_028",
      "deptId": "dep_cigs",
      "name": "פרלמנט סילבר",
      "price": 55.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93154f01a83e33234298ac",
      "imageAlt": "פרלמנט סילבר",
      "description": "יחידה",
      "order": 28
    },
    {
      "id": "prd_cigs_029",
      "deptId": "dep_cigs",
      "name": "כאמל צהוב סופט",
      "price": 44.9,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93155e01a83e33234298b2",
      "imageAlt": "כאמל צהוב סופט",
      "description": "יחידה",
      "order": 29
    },
    {
      "id": "prd_cigs_030",
      "deptId": "dep_cigs",
      "name": "כאמל צהוב",
      "price": 44.9,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9316423a9b0b41a1d1dbbc",
      "imageAlt": "כאמל צהוב",
      "description": "יחידה",
      "order": 30
    },
    {
      "id": "prd_cigs_031",
      "deptId": "dep_cigs",
      "name": "כאמל בלו",
      "price": 44.9,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9316543a9b0b41a1d1dbbe",
      "imageAlt": "כאמל בלו",
      "description": "יחידה",
      "order": 31
    },
    {
      "id": "prd_cigs_032",
      "deptId": "dep_cigs",
      "name": "ווינסטון אדום",
      "price": 47.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9316697b7d76e02824c157",
      "imageAlt": "ווינסטון אדום",
      "description": "יחידה",
      "order": 32
    },
    {
      "id": "prd_cigs_033",
      "deptId": "dep_cigs",
      "name": "ווינסטון בלו ארוך",
      "price": 47.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9316797b7d76e02824c15a",
      "imageAlt": "ווינסטון בלו ארוך",
      "description": "יחידה",
      "order": 33
    },
    {
      "id": "prd_cigs_034",
      "deptId": "dep_cigs",
      "name": "קורסט לילך",
      "price": 36.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9316f501a83e33234298bf",
      "imageAlt": "קורסט לילך",
      "description": "יחידה",
      "order": 34
    },
    {
      "id": "prd_cigs_035",
      "deptId": "dep_cigs",
      "name": "קורסט מנטול סלימס",
      "price": 36.8,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9317063a9b0b41a1d1dbc2",
      "imageAlt": "קורסט מנטול סלימס",
      "description": "יחידה",
      "order": 35
    },
    {
      "id": "prd_cigs_036",
      "deptId": "dep_cigs",
      "name": "דוידוף קלאסיק",
      "price": 46.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9317193a9b0b41a1d1dbc3",
      "imageAlt": "דוידוף קלאסיק",
      "description": "יחידה",
      "order": 36
    },
    {
      "id": "prd_cigs_037",
      "deptId": "dep_cigs",
      "name": "אל.די סופר סלימס בלו",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93172a3a9b0b41a1d1dbc5",
      "imageAlt": "אל.די סופר סלימס בלו",
      "description": "יחידה",
      "order": 37
    },
    {
      "id": "prd_cigs_038",
      "deptId": "dep_cigs",
      "name": "ווינסטון קומפקט בלו",
      "price": 40.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93173f7b7d76e02824c160",
      "imageAlt": "ווינסטון קומפקט בלו",
      "description": "יחידה",
      "order": 38
    },
    {
      "id": "prd_cigs_039",
      "deptId": "dep_cigs",
      "name": "ווינסטון קומפקט ברי",
      "price": 41.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9317b601a83e33234298cb",
      "imageAlt": "ווינסטון קומפקט ברי",
      "description": "יחידה",
      "order": 39
    },
    {
      "id": "prd_cigs_040",
      "deptId": "dep_cigs",
      "name": "אל.די כחול ארוך",
      "price": 41.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9317c801a83e33234298ce",
      "imageAlt": "אל.די כחול ארוך",
      "description": "יחידה",
      "order": 40
    },
    {
      "id": "prd_cigs_041",
      "deptId": "dep_cigs",
      "name": "אל.די אדום קצר",
      "price": 41.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9317d801a83e33234298cf",
      "imageAlt": "אל.די אדום קצר",
      "description": "יחידה",
      "order": 41
    },
    {
      "id": "prd_cigs_042",
      "deptId": "dep_cigs",
      "name": "אל.די כחול קצר",
      "price": 41.4,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9317ef01a83e33234298d0",
      "imageAlt": "אל.די כחול קצר",
      "description": "יחידה",
      "order": 42
    },
    {
      "id": "prd_cigs_043",
      "deptId": "dep_cigs",
      "name": "אל.די סלימס סגול",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a9317fe01a83e33234298d2",
      "imageAlt": "אל.די סלימס סגול",
      "description": "יחידה",
      "order": 43
    },
    {
      "id": "prd_cigs_044",
      "deptId": "dep_cigs",
      "name": "ווינסטון קוד",
      "price": 43.7,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a93181601a83e33234298d5",
      "imageAlt": "ווינסטון קוד",
      "description": "יחידה",
      "order": 44
    },
    {
      "id": "prd_cigs_045",
      "deptId": "dep_cigs",
      "name": "ווינסטון סלימס כחול",
      "price": 47.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a931a463a9b0b41a1d1dbdd",
      "imageAlt": "ווינסטון סלימס כחול",
      "description": "יחידה",
      "order": 45
    },
    {
      "id": "prd_cigs_046",
      "deptId": "dep_cigs",
      "name": "ווינסטון סלימס מנטול",
      "price": 47.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a931a543a9b0b41a1d1dbde",
      "imageAlt": "ווינסטון סלימס מנטול",
      "description": "יחידה",
      "order": 46
    },
    {
      "id": "prd_cigs_047",
      "deptId": "dep_cigs",
      "name": "פאל מאל סופר סלימס ויולט",
      "price": 43.7,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a931a623a9b0b41a1d1dbdf",
      "imageAlt": "פאל מאל סופר סלימס ויולט",
      "description": "יחידה",
      "order": 47
    },
    {
      "id": "prd_cigs_048",
      "deptId": "dep_cigs",
      "name": "פאל מאל דמי מינט",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a931a7001a83e33234298ed",
      "imageAlt": "פאל מאל דמי מינט",
      "description": "יחידה",
      "order": 48
    },
    {
      "id": "prd_cigs_049",
      "deptId": "dep_cigs",
      "name": "פאל מאל דמי ברי",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a931a7e01a83e33234298ee",
      "imageAlt": "פאל מאל דמי ברי",
      "description": "יחידה",
      "order": 49
    },
    {
      "id": "prd_cigs_050",
      "deptId": "dep_cigs",
      "name": "פאל מאל דמי בלובירי",
      "price": 39.1,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a931a8d01a83e33234298f0",
      "imageAlt": "פאל מאל דמי בלובירי",
      "description": "יחידה",
      "order": 50
    },
    {
      "id": "prd_lighters_001",
      "deptId": "dep_lighters",
      "name": "מצית",
      "price": 2.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3bc7381699254999dd27d7",
      "imageAlt": "מצית",
      "description": "יחידה",
      "order": 1
    },
    {
      "id": "prd_lighters_002",
      "deptId": "dep_lighters",
      "name": "5 מצתים ב-8 שקל",
      "price": 8.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a426f0eed9a075abfc400f0",
      "imageAlt": "5 מצתים ב-8 שקל",
      "description": "5 יחידות",
      "order": 2
    },
    {
      "id": "prd_lighters_003",
      "deptId": "dep_lighters",
      "name": "מצת טורבו ספינר",
      "price": 5.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3bbde31699254999dd2436",
      "imageAlt": "מצת טורבו ספינר",
      "description": "יחידה",
      "order": 3
    },
    {
      "id": "prd_lighters_004",
      "deptId": "dep_lighters",
      "name": "מצית קריקט קטנה",
      "price": 5.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3ba504c3bb1f158fe9e307",
      "imageAlt": "מצית קריקט קטנה",
      "description": "יחידה",
      "order": 4
    },
    {
      "id": "prd_lighters_005",
      "deptId": "dep_lighters",
      "name": "3 מצתי קריקט קטן ב-12.5",
      "price": 12.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a426f0d087d6ded5520e8ac",
      "imageAlt": "3 מצתי קריקט קטן ב-12.5",
      "description": "3 יחידות",
      "order": 5
    },
    {
      "id": "prd_lighters_006",
      "deptId": "dep_lighters",
      "name": "מצת קריקט",
      "price": 5.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3faf05cdc8c6bbaf6dbffe",
      "imageAlt": "מצת קריקט",
      "description": "יחידה",
      "order": 6
    },
    {
      "id": "prd_lighters_007",
      "deptId": "dep_lighters",
      "name": "3 מצתי קריקט גדול ב-12.5",
      "price": 12.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a426f0eed9a075abfc400ef",
      "imageAlt": "3 מצתי קריקט גדול ב-12.5",
      "description": "3 יחידות",
      "order": 7
    },
    {
      "id": "prd_lighters_008",
      "deptId": "dep_lighters",
      "name": "מצת קליפר",
      "price": 6.2,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3d969f773218380cd618b5",
      "imageAlt": "מצת קליפר",
      "description": "יחידה",
      "order": 8
    },
    {
      "id": "prd_lighters_009",
      "deptId": "dep_lighters",
      "name": "3 קליפרים ב-12.5 שקל",
      "price": 12.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a426f0fed9a075abfc400f1",
      "imageAlt": "3 קליפרים ב-12.5 שקל",
      "description": "3 יחידות",
      "order": 9
    },
    {
      "id": "prd_lighters_010",
      "deptId": "dep_lighters",
      "name": "מצית טורבו זהב",
      "price": 9.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3bcdbc1eb69a0aa2254ec1",
      "imageAlt": "מצית טורבו זהב",
      "description": "יחידה",
      "order": 10
    },
    {
      "id": "prd_lighters_011",
      "deptId": "dep_lighters",
      "name": "מצת טורבו גראס",
      "price": 10.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3bbad5c3bb1f158fe9ef33",
      "imageAlt": "מצת טורבו גראס",
      "description": "יחידה",
      "order": 11
    },
    {
      "id": "prd_lighters_012",
      "deptId": "dep_lighters",
      "name": "מצית קליפר ג'ט טורבו",
      "price": 12.5,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3ba30c1699254999dd124f",
      "imageAlt": "מצית קליפר ג'ט טורבו",
      "description": "יחידה",
      "order": 12
    },
    {
      "id": "prd_lighters_013",
      "deptId": "dep_lighters",
      "name": "מצית גז מטבח ארוכה",
      "price": 16.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3faeb6cdc8c6bbaf6dbfef",
      "imageAlt": "מצית גז מטבח ארוכה",
      "description": "יחידה",
      "order": 13
    },
    {
      "id": "prd_lighters_014",
      "deptId": "dep_lighters",
      "name": "מצית מטבח ארוכה מתקפלת",
      "price": 16.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3faefbcdc8c6bbaf6dbffc",
      "imageAlt": "מצית מטבח ארוכה מתקפלת",
      "description": "יחידה",
      "order": 14
    },
    {
      "id": "prd_lighters_015",
      "deptId": "dep_lighters",
      "name": "מצת טורבו 3 להבות",
      "price": 18.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3bc25ac3bb1f158fe9f305",
      "imageAlt": "מצת טורבו 3 להבות",
      "description": "יחידה",
      "order": 15
    },
    {
      "id": "prd_lighters_016",
      "deptId": "dep_lighters",
      "name": "מצת קליפר ברזל טורבו ג'ט, כסוף עם קופסא",
      "price": 43.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a5541df13b9d66967401941",
      "imageAlt": "מצת קליפר ברזל טורבו ג'ט, כסוף עם קופסא",
      "description": "יחידה",
      "order": 16
    },
    {
      "id": "prd_lighters_017",
      "deptId": "dep_lighters",
      "name": "מצית קליפר מתכת בעיצוב גולגולות, עם קופסא",
      "price": 43.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a3ba21a1eb69a0aa22536a5",
      "imageAlt": "מצית קליפר מתכת בעיצוב גולגולות, עם קופסא",
      "description": "יחידה",
      "order": 17
    },
    {
      "id": "prd_lighters_018",
      "deptId": "dep_lighters",
      "name": "מילוי גז מצתים",
      "price": 16.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a0184cd52a81beed35c9a73",
      "imageAlt": "מילוי גז מצתים",
      "description": "יחידה",
      "order": 18
    },
    {
      "id": "prd_lighters_019",
      "deptId": "dep_lighters",
      "name": "דלק זיפו",
      "price": 21.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a0184cd52a81beed35c9a4f",
      "imageAlt": "דלק זיפו",
      "description": "יחידה",
      "order": 19
    },
    {
      "id": "prd_lighters_020",
      "deptId": "dep_lighters",
      "name": "בלון מילוי גז קוליברי",
      "price": 37.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a436faa9943d1d78ddac8d1",
      "imageAlt": "בלון מילוי גז קוליברי",
      "description": "יחידה",
      "order": 20
    },
    {
      "id": "prd_lighters_021",
      "deptId": "dep_lighters",
      "name": "מיכל גז בוטאן לברנר או לכירת גז",
      "price": 20.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a882416bccbc4de23e08b59",
      "imageAlt": "מיכל גז בוטאן לברנר או לכירת גז",
      "description": "יחידה",
      "order": 21
    },
    {
      "id": "prd_lighters_022",
      "deptId": "dep_lighters",
      "name": "מצת טורבו ברנר גדול אקדח AN",
      "price": 30.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a0184cd52a81beed35c9a77",
      "imageAlt": "מצת טורבו ברנר גדול אקדח AN",
      "description": "יחידה",
      "order": 22
    },
    {
      "id": "prd_lighters_023",
      "deptId": "dep_lighters",
      "name": "מצת קוליברי אוו להבה אחת",
      "price": 345.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a5f1804148de55ae16f0e37",
      "imageAlt": "מצת קוליברי אוו להבה אחת",
      "description": "יחידה",
      "order": 23
    },
    {
      "id": "prd_lighters_024",
      "deptId": "dep_lighters",
      "name": "מצת קוליברי אאורה עט",
      "price": 350.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a5f1e86ca398677dbafd0e1",
      "imageAlt": "מצת קוליברי אאורה עט",
      "description": "יחידה",
      "order": 24
    },
    {
      "id": "prd_lighters_025",
      "deptId": "dep_lighters",
      "name": "מצת קוליברי SLIM להבה אחת",
      "price": 385.0,
      "prevPrice": null,
      "stock": "in",
      "image": "https://imageproxy.wolt.com/assets/6a5f180f148de55ae16f0e38",
      "imageAlt": "מצת קוליברי SLIM להבה אחת",
      "description": "יחידה",
      "order": 25
    }
  ],
  "settings": {
    "smokingWarning": "אזהרה: העישון מזיק לבריאות ומכיל חומרים ממכרים",
    "ageNotice": "מכירת מוצרי טבק ועישון אסורה מתחת לגיל 18. תידרש הצגת תעודה מזהה במעמד המסירה.",
    "vatNotice": "כל המחירים לצרכן כוללים מס ערך מוסף.",
    "ageGate": true,
    "checkout": {
      "enabled": true,
      "deliveryFee": 20,
      "freeDeliveryFrom": 0,
      "minOrder": 0,
      "pickupAddress": "הזגג 11, אילת",
      "deliveryAreas": "אילת והסביבה",
      "payCash": true,
      "payCardOnDelivery": true,
      "payLink": "",
      "payLinkLabel": "קישור תשלום מאובטח"
    }
  }
};
